### ISSUE TITLE
Can't use fos:user:create 

### ISSUE THREAD

**Issue by Guillawme** [bardius/BardisCMS#14]
When we want to create user or super-admin in command line, there is a bug:

`$ php app/console fos:user:create guillaum --super-admin

[Doctrine\DBAL\Driver\PDOException]                                                           
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'terms_accepted' cannot be null`

**Comment by bardius** [comment]
Please use the UserBundle DataFixtures to create your users, as per the existing example ones, since the uses entity has be enhanced with extra fields that are required.

**Comment by bardius** [comment]
Hello @Guillawme,

Regardless, I have lifted the not null constraint from the fields that where causing the issue so you can now create your user as expected with

`php app/console fos:user:create guillaum --super-admin`
